# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-13 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='birthday',
            field=models.DateField(default='2016-10-10'),
            preserve_default=False,
        ),
    ]
