# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_show',
            name='desc',
            field=models.TextField(default='This is a new Movies '),
            preserve_default=False,
        ),
    ]
